### ISSUE TITLE
Typical URL Warning: not For Facebook

### ISSUE THREAD

**Issue by cogdog** [oeru/blog-feed-finder#1]
Liking the response for commonly edited URLs, but expected to see it from Readme.md for entering http://facebook.com, it just offers that it redirects.

Also, and minor, on the hover box that appears for the warning on Google.com, the box disappears before I can click the hyperlink (Google Chrome in Mac OSX)

![hover](https://user-images.githubusercontent.com/463038/41881331-3881ff02-78a0-11e8-816c-6375bcd99693.jpg)

**Comment by lightweight** [comment]
Thanks for the feedback! Yes, with http://facebook.com, it redirects to https... thus the first message. It then mentions (second mention) that it's a common error, doesn't it? Ah, no it doesn't. Looks like the regex I'm using isn't coping if there's a "/" on the end of the URL... will fix.

Regarding the tooltip, yes, that's a tricky one... the issue is that it's gotta work for both touch and mouse-driven interfaces... Need to work out a solution. I'll shift that link into the default message (that doesn't disappear)...

**Comment by cogdog** [comment]
Not getting the second message for FB on my test site https://extend-domains.ecampusontario.ca/blog-feed-finder/

![fb](https://user-images.githubusercontent.com/463038/41882340-af5c4592-78a5-11e8-86ad-a2075282fc44.jpg)

**Comment by lightweight** [comment]
Yes, in my testing, I also got that... Trying to work out what's going wrong... yes, have seen some weird behaviour - sometimes the process halts in a place that isn't final. I haven't yet been able to work out the conditions that lead to this problem. It doesn't always seem to happen.

**Comment by lightweight** [comment]
Ok, fixed all of this, including moving the clickable help URL into the main comment, not the tooltip.
